<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAuclmhh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAuclmhh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAuclmhh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAuclmhh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAuclmhh\appProdProjectContainer(array(
    'container.build_hash' => 'Auclmhh',
    'container.build_id' => '1d541586',
    'container.build_time' => 1550825601,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAuclmhh');
