<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJcbjexl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJcbjexl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJcbjexl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJcbjexl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJcbjexl\appProdProjectContainer(array(
    'container.build_hash' => 'Jcbjexl',
    'container.build_id' => '6b274f26',
    'container.build_time' => 1550393804,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJcbjexl');
